export const bottomright =document.querySelector('.header_bottom_right')
export const trees_container=document.querySelector('.trees_container')
export const carT=document.querySelector('.carT')
export const carimg=document.querySelector('.carimg')
export const about =document.querySelector('.about-us-images')
